name: Gerar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    name: Compilar APK
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Gerar build do React
        run: npm run build
        env:
            VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL}}
            VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY}}

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Dar permissão ao Gradle
        run: chmod +x android/gradlew

      - name: Gerar APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: di-salgados-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk